### ISSUE TITLE
Issues with "format_gwas" and "calculate_POET_sw"

### ISSUE THREAD

**Issue by emmawwinchester** [rujinwang/EPIC#1]
Hi Rujin!
I am trying to run through the vignette before applying to my data, and cannot get the formatting to work. 
1. I cannot get format_gwas to run. There are no immediate issues if I manually generate the "MAC" and "Zscore" columns (and manually assign column order) from the gwas.Demo input file (however, I end up with issues at the calculate_POET_sw step, which may be unrelated). Currently, if I try to run format_gwas on the gwas.Demo object as is, the output is an empty file (correct columns, but no single SNP passes into it).
Is this due to a wrong version of plink that I'm referencing (plink-1.07)? I pulled the same .bim file that was used in the demo. 
Thanks
Emma

**Comment by yuchaojiang** [comment]
@rujinwang Hi Rujin, can you check on this potential error and get back to @emmawwinchester ?

**Comment by rujinwang** [comment]
Hi @emmawwinchester , 
Thanks for your interest in EPIC. Sorry for the late reply. 

1. `format_gwas`: please make sure you specify `bfile_path` and `plink_path` correctly. Specifically, please ensure that `$plink_path/plink --bfile $bfile_path/g1000_eur --maf 0.00000001 --geno 0 --write-snplist` is runnable on terminal. Note here `$bfile_path` is the folder that contains g1000_eur.fam/bim/bed file. I used plink 1.90b. Not sure if it's due to the different versions we used. Please double check your bfile_path first. 
2. `calculate_POET_sw`: what's the issue you have with this function? I didn't get any errors following my tutorial example. This step takes time and would generate a lot of intermediate files. 

Please let me know if you have any more questions. Thanks. 

Best, 
Rujin

**Comment by emmawwinchester** [comment]
So by switching plink versions I was able to work around the issue! However I still end up with this error at the "gene_gene_chisq" step when working with the demo data: 
Error in seq.default(1, (nsnps - sliding_size + 1), sliding_step) :
  wrong sign in 'by' argument

**Comment by rujinwang** [comment]
Hi @emmawwinchester ,
I've fixed the bug. Please re-install the package and run the demo. For some reasons I'm not able to receive any email notifications from this repository. Apologies for delay in replying.  
Please note that our package is still in its beta version. We appreciate any feedback that helps improve the usage. Thanks!

Best, 
Rujin

**Comment by emmawwinchester** [comment]
Hi @rujinwang I am still getting this issue when running the "calculate_POET_sw" command on anything other than chr2, even with the demo dataset. All previous steps were run on all chromsomes. 

example:
calculate_POET_sw(genotype = X_ref.Demo, gene_pval = prunein_gene_pval.Demo, gene.loc = gtex.loc, type = "POET", inter_dir = inter_dir, chr=10)
Error in seq.default(1, (length(gene_pval) - sliding_size + 1), sliding_step) :
  wrong sign in 'by' argument


another example:
for (chrs in 1:22) {
calculate_POET_sw(genotype = X_ref.Demo, gene_pval = prunein_gene_pval.Demo, gene.loc = gtex.loc, type = "POET", inter_dir = inter_dir, chr=chrs)
}

Error in seq.default(1, (length(gene_pval) - sliding_size + 1), sliding_step) :
  wrong sign in 'by' argument

**Comment by emmawwinchester** [comment]
I just realized the demo dataset has only snps from chr2, lol. sorry for the bother!

**Comment by emmawwinchester** [comment]
@rujinwang I actually am still running into the error when trying anything except chrom 2, even with my own datasets. Same error of wrong sign in the argument. Sorry for all the confusion!! We forced the update even though there was a warning that there was no change to any script, so it seems github thinks there is no new version that should be downloaded (we tried to update the package both before and after I initially reported this bug, and got the same thing both times).

**Comment by rujinwang** [comment]
Hi @emmawwinchester , 
I'm sorry for the issues you have. Could you please try `remove.packages("EPIC")` and re-install? Please let me know how it works. Thanks.

**Comment by emmawwinchester** [comment]
@rujinwang retried it a few times, and still getting the error for anything other than chr 2!

**Comment by yuchaojiang** [comment]
@emmawwinchester Can you post your detailed script and error? Does our vignettes demonstrate on chr2 and you run that with no issue? But problems with other chromosomes? @rujinwang could you please help?

**Comment by emmawwinchester** [comment]
@yuchaojiang @rujinwang I will have to dig up the script to demonstrate, but essentially I can run successfully all of epic on chromosome 2, using either your demo dataset or our own data. There are no issues with this process when using chr2, but as soon as I try to use a different chromosome (or all chromosomes), we run into the error shown about with POET. This is the same case whether I use bulk RNAseq or scRNAseq data. If I run the command shown above using chr=2, it proceeds with no error.

**Comment by emmawwinchester** [comment]
detailed script: 



library(EPIC)
set.seed(123)
trait = "caries"
tail(gwas)
bfile_path <- "."
plink_path <- "/isg/shared/apps/plink/plink-1.07-x86_64"

snp<-read.table(file='EUR_DFSS_incl_HCHSSOL.txt', header=TRUE, sep='\t')
snp$Allele1<-gsub('c', 'C', gsub('g', 'G', gsub('a', 'A', gsub('t', 'T', snp$Allele1))))
snp$Allele2<-gsub('c', 'C', gsub('g', 'G', gsub('a', 'A', gsub('t', 'T', snp$Allele2))))
snp$pos<-gsub('*.:', '', snp$MarkerName)
snp$chr<-gsub(':.*', '', snp$MarkerName)
#snp<-snp[,c(4,8:10,16:17)]
snp<-snp[,c('chr', 'pos', 'Allele1', 'Allele2', 'Freq1', 'Effect', 'StdErr', 'P.value', 'N')]
snp$name<-paste(snp$chr, '_', snp$pos, sep='')
tab<-read.table('g1000_eur.bim', sep='\t')
colnames(tab)<-c('chr', 'rsid', 'cm', 'pos', 'Allele1', 'Allele2')
tab$name<-paste(tab$chr, tab$pos, sep='_')
snp2<-merge(snp, tab, by.x='name', by.y='name')
colnames(snp2)[c(2,3,4,5,6,7,8,9,10,12)]<-c('chr', 'pos', 'A1', 'A2', 'MAF', 'beta', 'se', 'P', 'N', 'rsid')
snp2<-snp2[grep('rs', snp2$rsid),]
snp2<-snp2[,c(2,3,4,5,6,7,8,9,10,12)]
snp2$Zscore<-snp2$beta/snp2$se
snp2$MAC<-snp2$N*snp2$MAF*2
snp2[which(snp2$MAF >= 0.5),c('MAF')]<-(1-snp2[which(snp2$MAF >= 0.5),c('MAF')])
write.table(snp2, file='/home/FCAM/ewentworth/cotney/analysis/gwas/EPIC/Caries_input.txt')

#use de_enhancers environment

library(EPIC)
set.seed(123)
library(EPIC)
trait = "caries"
tail(gwas)
bfile_path <- "."
plink_path <- "/isg/shared/apps/plink/plink-1.07-x86_64"
gwas.formatted <- read.table(file='/home/FCAM/ewentworth/cotney/analysis/gwas/EPIC/Caries_input.txt')
gwas.formatted$placeholder<-gwas.formatted$A1
gwas.formatted$A1[which(gwas.formatted$beta < 0)]<-gwas.formatted$A2[which(gwas.formatted$beta < 0)]
gwas.formatted$A2[which(gwas.formatted$beta < 0)]<-gwas.formatted$placeholder[which(gwas.formatted$beta < 0)]
gwas.formatted$beta<-abs(gwas.formatted$beta)
gwas.formatted$placeholder<-NULL
snp_to_gene <- map_snp_to_gene(gwas = gwas.formatted)
snp_division_obj <- divide_common_rare(gwas = gwas.formatted, snp_to_gene = snp_to_gene)
common_snp_to_gene <- snp_division_obj$common_snp_to_gene
rare_snp_to_gene <- snp_division_obj$rare_snp_to_gene

out_dir = "."
MAF <- 0.01
prunein_dir <- file.path(out_dir, "prunein", MAF)
prunein_snp_to_gene<-NULL

prunein_snp_to_gene <- LD_pruning(common_snp_to_gene, prunein_dir)

out_dir = "."
results_dir <- file.path(".", trait)
prunein_qc_snp_to_gene <- NULL
for (chr in 1:22) {
print(chr)
prunein_qc_snp_to_gene.chr <- second_pruning(prunein_snp_to_gene, plink_path, bfile_path, chr, prunein_dir)
save(prunein_qc_snp_to_gene.chr, file = file.path(results_dir, paste0(trait, "_prunein_", MAF, "_chr", chr, "_QC.rda")))
}
# Merge: after we are done with chromosomes 1-22
prunein_qc_snp_to_gene <- NULL
for (chr in 1:22) {
print(chr)
  load(file.path(results_dir, paste0(trait, "_prunein_", MAF, "_chr", chr, "_QC.rda")))
  prunein_qc_snp_to_gene <- c(prunein_qc_snp_to_gene, prunein_qc_snp_to_gene.chr)
}


prunein_qc_snp_to_gene <- second_pruning(prunein_snp_to_gene, plink_path, bfile_path,  prunein_dir)

prunein_gene_pval <- read_in(gwas = gwas.formatted, snp_to_gene = prunein_qc_snp_to_gene)
rare_gene_pval <- read_in(gwas = gwas.formatted, snp_to_gene = rare_snp_to_gene)

head(gtex.Demo)[,1:5]
###########note that this demo set is only genes on chr2
loc <- read.table(file = system.file("extdata", "gene.noMHC.loc", package = "EPIC"), 
                  sep = "\t", header = FALSE, stringsAsFactors = FALSE)
gtex.loc <- loc[loc$V1 %in% rownames(gtex.Demo), ]

library(Seurat)
BaronMatrix <- readRDS(url("https://storage.googleapis.com/cellid-cbl/BaronMatrix.rds"))
BaronMetaData <- readRDS(url("https://storage.googleapis.com/cellid-cbl/BaronMetaData.rds"))
Baron <- CreateSeuratObject(counts = BaronMatrix, project = "Baron", min.cells = 5, min.features = 200, meta.data = BaronMetaData)
scRNA.object <- process_scRNA(SeuratObject = Baron, meta_ct_col = "cell.type")
scRNA.rpkm <- scRNA.object$scRNA.rpkm
scRNA.loc <- scRNA.object$scRNA.loc
head(scRNA.rpkm)

library(genio)
file_bed <- file.path(".", "g1000_eur.bed")
file_bim <- file.path(".", "g1000_eur.bim")
file_fam <- file.path(".", "g1000_eur.fam")

bim <- read_bim(file_bim)
fam <- read_fam(file_fam)
genotype <- read_bed(file_bed, bim$id, fam$id)

X_ref <- genotype[match(bim$id, rownames(genotype)),]
inter_dir <- file.path(".", trait)

for (chrs in 1:22) {
print(chrs)
calculate_POET_sw(genotype = X_ref, gene_pval = prunein_qc_snp_to_gene.Demo, gene.loc = scRNA.loc, chr=20, type = "POET", sliding_size=10, inter_dir = inter_dir, sliding_step=1)
}
pruneinObject <- get_gene_chisq(gene_pval = prunein_gene_pval, gene.loc = scRNA.loc, type = "POET", inter_dir = inter_dir)
prunein_POET_gene_pval <- pruneinObject$gene_POET_pval
prunein_gene_corr.mat <- pruneinObject$gene_corr.mat
rare_gene_pval <- get_burden(genotype = X_ref, gene_pval = rare_gene_pval)
combine_gene_pval <- get_combined(prunein_gene_pval = prunein_gene_pval, rare_gene_pval = rare_gene_pval)


X_super <- construct_X_super(genotype = X_ref, rare_gene_pval = rare_gene_pval)
for (chrs in 1:22) {
calculate_POET_sw(genotype = X_ref, gene_pval = combine_gene_pval, gene.loc = scRNA.loc, type = "iPOET", X_super = X_super, inter_dir = inter_dir, chr=chrs)
}
combineObject <- get_gene_chisq(gene_pval = combine_gene_pval,  gene.loc = scRNA.loc, type = "iPOET", inter_dir = inter_dir)
combine_POET_gene_pval <- combineObject$gene_POET_pval
combine_gene_corr.mat <- combineObject$gene_corr.mat

gtex.enrichment <- prioritize_relevance(gene_pval = prunein_POET_gene_pval, gene_corr.mat = prunein_gene_corr.mat, gene_expr = scRNA.rpkm, gene.loc = scRNA.loc) 

gtex.enrichment.joint <- prioritize_relevance(gene_pval = combine_POET_gene_pval, gene_corr.mat = combine_gene_corr.mat,  gene_expr = scRNA.rpkm, gene.loc = scRNA.loc) 


enrichment_plot <- plot_relevance(gtex.enrichment.joint)
enrichment_plot

influential_test.liver <- influential_testing(gene_pval = combine_POET_gene_pval, gene_corr.mat = combine_gene_corr.mat, gene_expr = scRNA.rpkm, gene.loc = scRNA.loc, ct = "Liver")

influential.genes.liver = influential_test.liver$influential.genes
p.dfbeta.liver = influential_test.liver$p.dfbeta
p.dfbeta.liver

dev.off()

**Comment by rujinwang** [comment]
Hi @emmawwinchester , 
Sorry for the confusion. 
Please note that the demo dataset was only for chr2. Don't try to run other chromosomes on demo! 
Please remove `gtex.loc <- loc[loc$V1 %in% rownames(gtex.Demo), ]` in your script. `gtex.Demo` only contains chr2 genes. Make sure that the input `gene.loc` of function `calculate_POET_sw` has at least 10 genes on the chromosome you are testing for sliding window approach. Otherwise you will be errorred out. (Package has been bumped into a new version) 
I'm offline in most of this week and will be late in responses. Thank you for your patience!

Best, 
Rujin
